{
 "title": "Level 1 - Executive Dashboard",
 "tags": [
  "L1",
  "Executive"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "🚦 System Health (All Instances)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "📈 Total System Traffic (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Total TPS"
    }
   ]
  },
  {
   "title": "🚨 Global Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m])) / sum(rate(http_server_requests_seconds_count[1m]))) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "P95 Latency (ms)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le)) * 1000"
    }
   ]
  }
 ]
}